name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - '*'

env:
  IMAGE_NAME: aisbreaker/aisbreaker-proxy-server

  # set a tag extensions if the CI runs on a different fork than the original repo
  #
  # the && is a workarround because there is no support for a ternary (?) operator,
  # but the term after && may not be empty
  # (https://github.com/orgs/community/discussions/25725#discussioncomment-3248924)
  DOCKER_TAG_FIX: "${{ github.repository_owner != 'aisbreaker' && 'other-' || '' }}"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG_FIX }}latest
        if: github.ref == 'refs/heads/main'
      - name: Build and push Docker image with develop tag
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG_FIX }}dev
        if: github.ref != 'refs/heads/main'

