name: Publish

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-and-publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .npmrc file to publish to npm
      - name: Setup npm authentication
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Build and Publish all packages/modules to npm
        run: |
          echo "./build-and-publish-all-packages.sh"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      # Build and publish Docker image for packages/aisbreaker-server/
      - name: Login and push to hub.docker.com
        run: |
          export VERSION="0.0.0"
          cd packages/aisbreaker-server/
          docker build -t "aisbreaker/aisbreaker-server:${VERSION}" -t "aisbreaker/aisbreaker-server:latest" .
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
          docker push --all-tags

  publish-docker:
    runs-on: ubuntu-latest
    needs: build-and-publish-npm
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        #run: docker build -t my-image .
        run: echo "docker build -t my-image ."
      - name: Push Docker image
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      #    docker push my-image

